models/Pets.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "pets".
 *
 * @property integer $pUi
 * @property string $name
 * @property string $ownerEmail
 * @property string $owner
 * @property string $species
 * @property string $sex
 * @property date $birth
 * @property date $date
*/
class Pets extends ActiveRecord
{
    const STATUS_REQUEST =0;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pets';
    }

    public function rules()
    {
        return [
            [['name', 'ownerEmail', 'owner', 'species', 'sex', 'birth'], 'required'],
            ['death', 'safe'],
            ['ownerEmail', 'email'],
            ['ownerEmail', 'unique', 'message' => 'Этот email уже зарегистрирован.'],
        ];
    }
}

controllers/PetsController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\Pets;
use yii\web\Response;
use yii\widgets\ActiveForm;

class PetsController extends Controller
{
    public function actionIndex()
    {
        $query = Pets::find();

        $pagination = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $pets = $query->orderBy('pUi')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('index', [
            'pets' => $pets,
            'pagination' => $pagination,
        ]);
    }

    public function actionAjax()
    {
        $model = new Pets();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        } else {
            // либо страница отображается первый раз, либо есть ошибка в данных
            return $this->render('create', ['model' => $model]);
        }
    }

    public function actionCreate()
    {
        $model = new Pets();

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->save()) {
            // данные в $model удачно проверены

            // делаем что-то полезное с $model ...
 
            return $this->redirect(['index']);
        } else {
            // либо страница отображается первый раз, либо есть ошибка в данных
            return $this->render('create', ['model' => $model]);
        }
    }
}

views/pets/create.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
?>
<?php $form = ActiveForm::begin([
    'id' => 'create',
    'enableAjaxValidation' => true,
    'validationUrl' => Yii::$app->urlManager->createUrl('pets/ajax')
]); ?>

    <?= $form->field($model, 'name') ?>
    <?= $form->field($model, 'ownerEmail') ?>
    <?= $form->field($model, 'owner') ?>
    <?= $form->field($model, 'species') ?>
    <?= $form->field($model, 'sex') ?>
    <?php echo $form->field($model,'birth')->
    widget(DatePicker::className(),[
        'name' => 'birth',
        'value' => date('d-M-Y', strtotime('+2 days')),
        'options' => ['placeholder' => 'Select birth date ...'],
        'pluginOptions' => [
            'format' => 'yyyy-mm-dd',
            'todayHighlight' => true
        ]
    ]) ?>
    <?php echo $form->field($model,'death')->
    widget(DatePicker::className(),[
        'name' => 'death',
        'value' => date('d-M-Y', strtotime('+2 days')),
        'options' => ['placeholder' => 'Select death date ...'],
        'pluginOptions' => [
            'format' => 'yyyy-mm-dd',
            'todayHighlight' => true
        ]
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']) ?>
    </div>

<?php ActiveForm::end(); ?>

views/pets/index.php
<?php
use yii\helpers\Html;
use yii\widgets\LinkPager;
?>
<h1>Pets</h1>
<ul>
<?php foreach ($pets as $pet): ?>
    <li>
        <?= Html::encode("{$pet->pUi} ({$pet->name}) ({$pet->ownerEmail}) ({$pet->owner})({$pet->species}) ({$pet->sex}) ({$pet->birth})") ?>
        <?= $pet->death ?>
    </li>
<?php endforeach; ?>
</ul>

<?= LinkPager::widget(['pagination' => $pagination]) ?>